name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 9

      - name: Cache Maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: |
          chmod +x mvnw
          ./mvnw -B verify --file pom.xml

  maven_release:
    name: Maven Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message, '[release]')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 9
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Release
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: |
          export GPG_TTY=$(tty)
          git config user.name "${{ github.event.head_commit.committer.name }}"
          git config user.email "${{ github.event.head_commit.committer.email }}"
          mvn -B --file pom.xml release:prepare release:perform -Drepository.url=https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git -Darguments="-Drelease=true -Dmaven.site.skip=true"

  release:
    name: Release
    needs: maven_release
    runs-on: ubuntu-latest

    steps:
      - uses: oprypin/find-latest-tag@v1
        id: latest
        with:
          repository: ${{ github.repository }}
          prefix: v

      - name: Version
        id: version
        run: echo "::set-output name=VERSION::$(echo ${{ steps.latest.outputs.tag }} | sed 's/v//')"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest.outputs.tag }}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 9

      - name: Cache Maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: |
          chmod +x mvnw
          ./mvnw -B verify --file pom.xml -DskipTests

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload zip
        id: upload-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pomchecker-cli/target/distributions/pomchecker-cli-${{ steps.version.outputs.VERSION }}.zip
          asset_name: pomchecker-cli-${{ steps.version.outputs.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload tgz
        id: upload-tgz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pomchecker-cli/target/distributions/pomchecker-cli-${{ steps.version.outputs.VERSION }}.tar.gz
          asset_name: pomchecker-cli-${{ steps.version.outputs.VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload toolprovider
        id: upload-toolprovider
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pomchecker-toolprovider/target/pomchecker-toolprovider-${{ steps.version.outputs.VERSION }}.jar
          asset_name: pomchecker-toolprovider-${{ steps.version.outputs.VERSION }}.jar
          asset_content_type: application/java-archive

  site:
    name: Site
    needs: release
    runs-on: ubuntu-latest

    steps:
      - uses: oprypin/find-latest-tag@v1
        id: latest
        with:
          repository: ${{ github.repository }}
          prefix: v

      - name: Version
        id: version
        run: echo "::set-output name=VERSION::$(echo ${{ steps.latest.outputs.tag }} | sed 's/v//')"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest.outputs.tag }}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 9

      - name: Build site
        run: |
          chmod +x mvnw
          ./mvnw -B --file pom.xml site site:stage -DstagingDirectory="${{ runner.temp }}/site"

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: "${{ runner.temp }}/site"

  announce:
    name: Announce
    needs: site
    runs-on: ubuntu-latest

    steps:
      - uses: oprypin/find-latest-tag@v1
        id: latest
        with:
          repository: ${{ github.repository }}
          prefix: v

      - name: Version
        id: version
        run: echo "::set-output name=VERSION::$(echo ${{ steps.latest.outputs.tag }} | sed 's/v//')"

      - name: Announce
        uses: ethomson/send-tweet-action@v1
        with:
          status: "Release ${{ steps.latest.outputs.tag }} of ${{ github.repository }} has been published to Maven Central https://github.com/${{ github.repository }}"
          consumer-key: ${{ secrets.TWITTER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest.outputs.tag }}

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 9

      - name: Sdkman
        run: |
          chmod +x mvnw
          ./mvnw -B -pl :pomchecker -Psdkman -Dpomchecker.version=${{ steps.version.outputs.VERSION }} --file pom.xml

  earlyaccess:
    name: 'Early Access'
    if: github.event_name == 'push' && github.repository == 'kordamp/pomchecker' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 9

      - name: Cache Maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: |
          chmod +x mvnw
          ./mvnw -DskipTests verify --file pom.xml

      - name: 'Release early-access artifacts'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: 'early-access'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          title: "PomChecker Early-Access"
          files: |
            pomchecker-cli/target/distributions/*.zip
            pomchecker-cli/target/distributions/*.tar.gz
            pomchecker-toolprovider/target/pomchecker-toolprovider-*.jar
